rust-mobile/android-activity

android-activity/src/game_activity/mod.rs
android-activity/src/native_activity/mod.rs
examples/agdk-egui/Cargo.toml
examples/agdk-winit-wgpu/Cargo.toml
examples/na-mainloop/src/lib.rs
examples/na-winit-wgpu/Cargo.toml

"native-activity" builds were recently broken by bb8eeb705c which
this patch fixes.
The na-mainloop example has also been updated to verify this by
reducing the fake "render" timeout and also triggering a fake
render when an InputAvailable event is received.
Fixes: #12

native-activity: Fix InputAvailable support

---

android-activity/build.rs

`libc++.a` is just a simple link script `INPUT(-lc++_static -lc++abi)`. I made the build script match so we link to the complete C++ standard library.
Fixes https://github.com/rib/android-activity/issues/10.

Link the C++ standard library correctly.

---

android-activity/game-activity-csrc/game-activity/native_app_glue/android_native_app_glue.c
android-activity/game-activity-csrc/game-activity/native_app_glue/android_native_app_glue.h
android-activity/src/game_activity/ffi_aarch64.rs
android-activity/src/game_activity/ffi_arm.rs
android-activity/src/game_activity/ffi_i686.rs
android-activity/src/game_activity/ffi_x86_64.rs
android-activity/src/game_activity/mod.rs
examples/agdk-mainloop/.idea/gradle.xml
examples/agdk-mainloop/src/lib.rs

This makes a small change to the C glue code for GameActivity to send
looper wake ups when new input is received (only sending a single wake
up, until the application next handles input).
When a wake up is received and we recognise that new input is available
then an `InputAvailable` event is sent to the application - consistent
with how NativeActivity can deliver `InputAvailable` events.
This addresses a significant feature disparity between GameActivity and
NativeActivity that meant GameActivity was not practically usable for
GUI applications that wouldn't want to render continuously like a game.
Addresses #4

Supports InputAvailable events with GameActivity

---

android-activity/CHANGELOG.md
android-activity/src/config.rs
android-activity/src/game_activity/mod.rs
android-activity/src/lib.rs
android-activity/src/native_activity/mod.rs
examples/agdk-egui/.idea/gradle.xml
examples/agdk-egui/Cargo.toml
examples/agdk-mainloop/src/lib.rs
examples/agdk-winit-wgpu/.idea/gradle.xml
examples/na-mainloop/.idea/gradle.xml
examples/na-mainloop/src/lib.rs

A number of API cleanups made while updating the Winit backend and dealing with some TODO items to try and reduce the chance of needing API breakages in the future.
- To make it possible to hold a reference to the AndroidApp within a Winit `Window` or `MonitorHandle` (for access to native_window and config state) the app structure is now `Send` + `Sync`.
- To avoid needing a static global Configuration in the Winit backend it's now possible to access a `ConfigurationRef` which is cheap to clone, Send + Sync and gives access to the application configuration without needing to make deep copies of the large `Configuration` struct
- The `NativeWindowRef` type was removed since it's become redundant now that `NativeWindow` implements `Clone` and `Drop`
- `FdEvent` and `Error` were unused …

Api cleanup for winit

---

android-activity/src/game_activity/mod.rs
android-activity/src/lib.rs
android-activity/src/native_activity/mod.rs

This enables support for changing the various WindowManager parameters documented here:
https://developer.android.com/reference/android/view/WindowManager.LayoutParams
either via NativeActivity_setWindowFlags or GameActivity_setWindowFlags
Fixes: #25

Support changing window manager params

---

android-activity/src/game_activity/mod.rs
android-activity/src/lib.rs
android-activity/src/native_activity/mod.rs

This is intended to be a stepping stone for addressing #18, considering the issues hit when testing https://github.com/rib/android-activity/pull/24

Add show/hide_soft_input methods + enable `InputEvent` forwards compatibility

---

android-activity/CHANGELOG.md
android-activity/src/game_activity/mod.rs
android-activity/src/lib.rs
android-activity/src/native_activity/mod.rs
examples/agdk-cpal/src/lib.rs
examples/agdk-eframe/Cargo.lock
examples/agdk-eframe/Cargo.toml
examples/agdk-egui/Cargo.lock
examples/agdk-egui/Cargo.toml
examples/agdk-mainloop/src/lib.rs
examples/agdk-oboe/src/audio.rs
examples/agdk-oboe/src/lib.rs
examples/agdk-winit-wgpu/Cargo.lock
examples/agdk-winit-wgpu/Cargo.toml
examples/na-mainloop/src/lib.rs
examples/na-subclass-jni/src/lib.rs
examples/na-winit-wgpu/Cargo.lock
examples/na-winit-wgpu/Cargo.toml

The callback given to `AndroidApp::input_events()` is now expected to return `InputStatus::Handled` or `InputStatus::Unhandled`.
When running with NativeActivity then if we know an input event hasn't been handled we can notify the InputQueue which may result in fallback handling.
Although the status is currently ignored with the GameActivity backend.
Fixes: #31

Let applications report if they handled input events

---

examples/agdk-cpal/Cargo.lock
examples/agdk-eframe/Cargo.lock
examples/agdk-eframe/Cargo.toml
examples/agdk-eframe/src/lib.rs
examples/agdk-egui/Cargo.lock
examples/agdk-egui/Cargo.toml
examples/agdk-egui/src/lib.rs
examples/agdk-mainloop/Cargo.lock
examples/agdk-oboe/Cargo.lock
examples/agdk-winit-wgpu/Cargo.lock
examples/agdk-winit-wgpu/Cargo.toml
examples/agdk-winit-wgpu/src/lib.rs
examples/na-mainloop/Cargo.lock
examples/na-openxr-info/Cargo.lock
examples/na-openxr-wgpu/Cargo.lock
examples/na-subclass-jni/Cargo.lock
examples/na-winit-wgpu/Cargo.lock
examples/na-winit-wgpu/Cargo.toml
examples/na-winit-wgpu/src/lib.rs

The winit based examples no longer have an explicit dependency on android-activity and they instead consume the `android-activity` API via the Winit crate so there's no need to keep the versions synchronized.

Update example deps + update for latest winit branch

---

android-activity/game-activity-csrc/game-activity/GameActivity.cpp
android-activity/game-activity-csrc/game-activity/GameActivity.h
android-activity/src/game_activity/ffi_aarch64.rs
android-activity/src/game_activity/ffi_arm.rs
android-activity/src/game_activity/ffi_i686.rs
android-activity/src/game_activity/ffi_x86_64.rs
android-activity/src/game_activity/input.rs

This maintains compatibility with the `ndk` crate's `Pointer` API
Ref: https://github.com/rust-windowing/android-ndk-rs/pull/323
This will also be required for enabling pen pressure support to
Winit, re: https://github.com/rust-windowing/winit/pull/2396

game_activity/input: support Pointer::tool_type()

---

android-activity/src/lib.rs

In a raw string [no escaping is processed] nor are these quotes treated specially unless it was postfixed with `#`; the backslashes show up in the compiler error displayed to the user instead.
For consistency the string this was likely copied from is now also turned into a raw string literal, with backslashes equivalently removed.
[no escaping is processed]: https://doc.rust-lang.org/reference/tokens.html#raw-string-literals

Remove backslash-escaping of quotes in raw string

---

android-activity/src/native_activity/glue.rs
android-activity/src/native_activity/mod.rs

Ideally information - especially when spamming per `Looper` poll - used for debugging `android-activity` doesn't show to the user unless they use the `Trace` level (eventually for this specific crate/module).  This is already adhered to in most places of the code but there were a few high-volume cases still remaining.

native_activity: Demote spammy `info!`/`eprintln!` debug logs to `trace!`

---

android-activity/CHANGELOG.md
android-activity/src/game_activity/mod.rs
android-activity/src/lib.rs
android-activity/src/native_activity/mod.rs

This enables applications to make JNI calls without needing the `ndk-context` crate - which we would like to deprecate.
For now this just exposes the raw pointers, and makes no assumptions about what crates an application will use to make JNI calls - which means that some amount of `unsafe` code will be required when passing these to other crates.
The added `_as_ptr()` suffix makes this clear, and also means we can consider adding similar (suffix-free) getters later that would return `jni` crate types that could reduce the need for unsafe code before making JNI calls.
Fixes: #60

Add AndroidApp::vm_as_ptr() and ::activity_as_ptr() APIs

---

android-activity/CHANGELOG.md
android-activity/Cargo.toml

No big changes, but it would be good to propagate the URL changes since migrating to `rust-mobile` as well as the APIs exposing the `JavaVM` + `Activity` pointers and removal of verbose logging in the `native-activity` backend.
Cc: @MarijnS95

Release 0.4.1

---

.github/workflows/ci.yml
README.md
android-activity/Cargo.toml

This also updates the CI to test with `cargo-ndk` 2, which compiles with rustc 1.64 (whereas v3 requires 1.68)

Add MSRV policy to README and bump `rust_version` to 0.64, due to `ndk` -> `raw_window_handle` dependency

---

.github/workflows/ci.yml
android-activity/Cargo.toml

Also removes a stale comment about MSVR policy in ci.yml
This addresses a couple of things from https://github.com/rust-mobile/android-activity/pull/76
Cc: @MarijnS95

Fix rust_version typo s/0.64/1.64/

---

android-activity/src/game_activity/mod.rs
android-activity/src/native_activity/glue.rs
android-activity/src/util.rs

Prevents undefined behavior in the event that any functions panic.

Add panic guards to extern "C" functions

---

android-activity/src/game_activity/input.rs

Given `AMOTION_EVENT_ACTION_MASK` is 0xff and `AMOTION_EVENT_ACTION_POINTER_INDEX_MASK` is 0xff00, this function always returns 0. Looks like ANDing with `AMOTION_EVENT_ACTION_MASK` should be removed.

game_activity: Fix `pointer_index()` always returning `0`

---

android-activity/CHANGELOG.md
android-activity/src/game_activity/mod.rs
android-activity/src/native_activity/glue.rs
android-activity/src/util.rs

Calling Activity.finish() is what ensures the Activity will get gracefully destroyed, including calling the Activity's onDestroy method.
Fixes: #67

Call Activity.finish() when android_main returns

---

android-activity/Cargo.toml

Cargo complains:
warning: android-activity/Cargo.toml: unused manifest key: package.rust_version
Solve this by replacing the underscore with a hyphen.

cargo: Fix `rust_version` -> `rust-version` property typo

---

android-activity/src/native_activity/glue.rs

Fix a deadlock that occurs when an activity is destroyed without process termination, such as when an activity is destroyed and recreated due to a configuration change.
The deadlock occurs because `notify_destroyed` blocks until `destroyed` is set to `true`. This only occurs when `WaitableNativeActivityState` is dropped, but the `WaitableNativeActivityState` instance is the very thing being used to await for destruction, resulting in a deadlock.
This doesn't really make much sense, so instead, wait for the Rust-side main thread to terminate to ensure cleanup can proceed.

Fix deadlock on activity onDestroy

---

android-activity/build.rs
android-activity/game-activity-csrc/game-activity/native_app_glue/android_native_app_glue.c

This ensures that any java Activity callbacks take into account the possibility that the `android_app` may have already been marked destroyed if `android_main` has returned - and so they mustn't block and wait for a thread that is no longer running.
Fixes: #97

GameActivity PATH: fix deadlocks in java callbacks after app destroyed

---

android-activity/CHANGELOG.md
android-activity/Cargo.toml

Fixes a number of dead locks that can happen after returning from `android_main` and destroying the Activity.

Release 0.4.3

---

android-activity/src/game_activity/input.rs

It was a mistake to expose a public Deref implementation for the `KeyEvent` and `MotionEvent` types for the GameActivity backend.
It was very surprising to see these Winit changes temporarily rely on this: https://github.com/rust-windowing/winit/commit/918430979f8219648daade44796c00893e42fdd8#diff-9169a22d6397a250be741006cd857b8a575f804c74cc07e3a4fb8f3341606d9b
Fixes: #91

game-activity: Remove Deref implementations for Key/MotionEvent types

---

android-activity/Cargo.toml
android-activity/game-activity-csrc/game-activity/native_app_glue/android_native_app_glue.c
android-activity/src/game_activity/input.rs
android-activity/src/game_activity/mod.rs
android-activity/src/input.rs
android-activity/src/lib.rs
android-activity/src/native_activity/input.rs
android-activity/src/native_activity/mod.rs

Add input method support based on the GameTextInput library (only supported with `game-activity` currently)
This is based on discussion for #18 and [here](https://github.com/rib/android-activity/pull/21)

Input method (soft keyboard) support

---

android-activity/Cargo.toml
android-activity/src/input.rs
android-activity/src/lib.rs

Changelog: https://github.com/bitflags/bitflags/blob/2.0.0/CHANGELOG.md#200.
This is a breaking change. The API that is implemented by the macro is now different.
I was a bit liberal with deriving `std` traits on public types, which mimics the behavior of `bitflags` v1, let me know if we don't need all these traits. Potentially we could at least drop `PartialOrd` and `Ord`.
[Replaces https://github.com/zakarumych/gpu-alloc/pull/70](https://github.com/rust-mobile/android-activity/pull/83).

Bump `bitflags` to v2

---

.github/workflows/ci.yml
android-activity/Cargo.toml
android-activity/src/game_activity/mod.rs
android-activity/src/native_activity/glue.rs

- Lets us build with cargo ndk 3+
- Lets us remove suppression for false-negative clippy warning about unsafe blocks in unsafe functions
- Should unblock CI for #102
- 1.68.0 notably also builds the standard library with a newer r25 NDK toolchain which avoids the need for awkward libgcc workarounds, so it's anyway a desirable baseline for Android projects.

Bump MSRV to 1.68

---

.github/workflows/ci.yml
android-activity/Cargo.toml
android-activity/src/game_activity/mod.rs
android-activity/src/native_activity/glue.rs

This effectively reverts 66cfc68dac2a28e584c02f0ee4278fa7376aafee (from #103) and adds some comments explaining that we're currently blocked by Winit's MSRV policy + CI from being able to increase our rust-version.
This is a frustrating conflict that I hope can be addressed by updating Winit's CI system to allow different platforms to require more recent versions of Rust (which notably isn't in conflict with setting a conservative rust-version in Winit for supporting Debian on Linux)
This re-instates building android-activity with cargo-ndk 2 because building on Android with 1.64 requires a linker workaround that's not implemented in newer version of cargo-ndk.
This also reinstates the clippy false-negative warning suppression for unsafe blocks. Again it's frustrating that we can't have …

Revert 'Bump MSRV to 1.68'

---

android-activity/CHANGELOG.md
android-activity/Cargo.toml
android-activity/LICENSE
android-activity/src/error.rs
android-activity/src/game_activity/input.rs
android-activity/src/game_activity/mod.rs
android-activity/src/input.rs
android-activity/src/input/sdk.rs
android-activity/src/jni_utils.rs
android-activity/src/lib.rs
android-activity/src/native_activity/glue.rs
android-activity/src/native_activity/input.rs
android-activity/src/native_activity/mod.rs
examples/agdk-mainloop/src/lib.rs
examples/na-mainloop/src/lib.rs

_(Note: I've marked as draft while I still need to update the docs more)_
With the way events are delivered via an `InputQueue` with `NativeActivity` there is no direct access to the underlying KeyEvent and MotionEvent Java objects and no `ndk` API that supports the equivalent of `KeyEvent.getUnicodeChar()`
What `getUnicodeChar` does under the hood though is lookup into a `KeyCharacterMap` for the corresponding `InputDevice` based on the event's `key_code` and `meta_state` - which we can do via some JNI bindings for `KeyCharacterMap`.
Although it's still awkward to expose an API like
`key_event.get_unicode_char()` we can instead provide an API that lets you look up a `KeyCharacterMap` for any `device_id` and applications can then use that for character mapping.
This approach is also more …

Rework `input_events` API and expose `KeyCharacterMap` bindings

---

android-activity/game-activity-csrc/game-activity/GameActivityEvents.cpp
android-activity/game-activity-csrc/game-activity/GameActivityEvents.h
android-activity/src/game_activity/ffi_aarch64.rs
android-activity/src/game_activity/ffi_arm.rs
android-activity/src/game_activity/ffi_i686.rs
android-activity/src/game_activity/ffi_x86_64.rs

The `unicodeChar` in `GameActivityKeyEvent` wasn't being exposed by `android-activity` because we couldn't expose the unicode character in the same way with the native-activity backend - due to how events are received via an `InputQueue` that doesn't expose the underlying Java references for the key events.
Now that we have a consistent way of supporting unicode character mapping via `KeyCharacterMap` bindings it's redundant for the `GameActivity` backend to call `getUnicodeChar` automatically for each key press.

GameActivity PATCH: Don't read unicode via getUnicodeChar

---

.github/workflows/ci.yml
android-activity/Cargo.toml
examples/agdk-mainloop/.idea/misc.xml

_(I accidentally merged the [last PR](https://github.com/rust-mobile/android-activity/pull/111) into the input changes it was stacked on)_
Addresses; #109

Release 0.5.0 beta.0

---

.github/workflows/ci.yml

Enabling CI on all branches makes it smoother for external contributors, who can check CI status before creating a PR and awaiting approval of a workflow run.
For pull requests the behaviour in this repository is the same - a workflow run on a PR still requires approval. But for forks, this helps out with faster CI feedback.

Enable CI on all branches

---

android-activity/src/game_activity/input.rs
android-activity/src/input.rs
android-activity/src/native_activity/input.rs

See #121, which this PR replaces.
I did this as a quick sketch, can check it more carefully tomorrow, but wanted to check for your thoughts on this approach.
What do you think having a single `impl`, with `#[cfg(feature = "game/native-activity")]` checks inside the method, instead of mirroring two `impl`:s? In this case I personally think it reads better, and guarantees exact equality in the public API and its documentation, but I can change it if desired!

Avoid exposing Pointer and PointersIter from ndk

---

android-activity/src/game_activity/mod.rs
android-activity/src/native_activity/glue.rs

When the input file descriptor of the `pipe()` is `dup2()`'d into `stdin` and `stdout` it is effectively copied, leaving the original file descriptor open and leaking at the end of these statements.  Only the output file descriptor has its ownership transferred to `File` and will be cleaned up properly.
This should cause the reading end to read EOF and return zero bytes when `stdin` and `stdout` is open, rather than remaining open "indefinitely" (barring the whole process being taken down) as there will always be that one file descriptor referencing the input end of the pipe.

Close `logpipe` input file descriptor after `dup2()`

---

android-activity/src/game_activity/input.rs
android-activity/src/game_activity/mod.rs
android-activity/src/input.rs
android-activity/src/input/sdk.rs
android-activity/src/lib.rs
android-activity/src/native_activity/input.rs

This adds a `#[doc(hidden)]` `__Unknown(u32)` variant to the various enums to keep them extensible without requiring API breaks.
We need to consider that most enums that are based on Android SDK enums may be extended across different versions of Android (i.e. effectively at runtime) or extended in new versions of `android-activity` when we pull in the latest NDK/SDK constants.
In particular in the case that there is some unknown variant we at least want to be able to preserve the integer value to allow the values to be either passed back into the SDK (it doesn't always matter whether we know the semantics of a variant at compile time) or passed on to something downstream that could be independently updated to know the semantics.
We don't want it to be an API break to extend these enums in …

Improve forwards compatibility of input API

---

android-activity/src/lib.rs

Document that `AndroidApp` is cheaply cloneable

---

Cargo.toml

Since we're using `edition = "2021"` in `android-activity/Cargo.toml` (which defaults to the v2 resolver) then cargo warns that this isn't consistent with the v1 resolver default for the top-level workspace.

Set `workspace.resolver = "2"` and avoid cargo warning

---

android-activity/src/game_activity/input.rs
android-activity/src/input.rs
android-activity/src/native_activity/input.rs

This exposes the button associated with a button press or release action.
The PR also includes a separate copy&paste fix for `MotionEvent::action()` that was spotted while adding `action_button()`.

Expose MotionEvent::action_button() state

---

android-activity/Cargo.toml

Fixes #141
The `ndk` crate enables `raw-window-handle 0.6` by default (because of https://github.com/rust-mobile/ndk/pull/434#issuecomment-1752089087) which might not be used by consumers of the `android-activity` crate at all, or might (still) be a mismatching version. Even if the `rwh_0x` features are additive, figuring that out leads to cryptic errors and it is best to turn off these defaults completely and leave it to the user to turn it back on in their own `[dependencies]` section if desired.
---
I couldn't run the test because of that error, I'm on mac, not sure how my android dev setup is right now 😅

Disable `ndk` default features to remove `raw-window-handle 0.6`

---

android-activity/src/game_activity/mod.rs
android-activity/src/native_activity/glue.rs
android-activity/src/util.rs

Fixes #132
When `read_line()` starts returning `Err` the current `if let Ok` condition ignores those, likely causing the `loop` to spin indefinitely while this function keeps returning errors.
Note that we don't currently store the join handle for this thread anywhere, so won't see the error surface either (just like how the join handle for the main thread is never checked).  Perhaps we should call `log::error!()` to make the user aware that their IO logging has mysteriously terminated.

Stop log-forwarding thread on IO errors

---

android-activity/src/game_activity/mod.rs
android-activity/src/native_activity/glue.rs

Name spawned threads to make things more clear during debugging and profiling.
[Max thread name is 15](https://stackoverflow.com/questions/5026531/thread-name-longer-than-15-chars), so we can't fit more descriptive names like `android-activity-main` (but open for some other naming scheme).

Name spawned threads

---

android-activity/CHANGELOG.md
android-activity/Cargo.toml

Cc: @Vrixyz, @MeoMix, @MarijnS95

Release 0.5.1

---

android-activity/src/native_activity/input.rs

Partially fixes #146. Possibly fully fixes the issue as I haven't encountered any issues with multitouch positions with winit on Android.

native-activity/input: OR with `EVENT_ACTION_MASK` when extracting action

---

.github/workflows/ci.yml
android-activity/CHANGELOG.md
android-activity/Cargo.toml

cargo ndk will fail to build with 1.68 due to a toml_edit dep.
Technically android-activity itself should still build with 1.68 but it's simpler to synchronize the `rust-version` with the minimum version that we actually test in CI (where we need to build cargo ndk)

Bump MSRV to 1.69.0 considering we can't build cargo ndk with 1.68

---

android-activity/Cargo.toml
android-activity/src/native_activity/input.rs
android-activity/src/native_activity/mod.rs
examples/agdk-mainloop/Cargo.toml
examples/na-mainloop/Cargo.toml

The next breaking `ndk` release puts a lot of emphasis in improving `enum`s to finally be marked `non_exhaustive`, and carry possible future values in `__Unknown(i32)` variants.  This removes the lossy conversions that previously required `android-activity` to redefine its types, which could all be removed again.
The `repr()` types have also been updated, as `enum` constants in C are translated to `u32` by default in `bindgen` even though they're commonly passed as `int` to every API function that consumes them.

Upgrade to `ndk-sys 0.6.0` and `ndk 0.9.0`

---

android-activity/src/native_activity/glue.rs

Avoids calling `std::slice::from_raw_parts` with a null `saved_state_in` pointer.
Fixes: #153

native-activity: Check for null saved_state_in pointer

---

.github/workflows/ci.yml
android-activity/Cargo.toml
android-activity/src/config.rs
android-activity/src/game_activity/ffi.rs
android-activity/src/game_activity/input.rs
android-activity/src/game_activity/mod.rs
android-activity/src/input.rs
android-activity/src/lib.rs
android-activity/src/native_activity/glue.rs
android-activity/src/native_activity/input.rs
android-activity/src/native_activity/mod.rs

[Rust 1.80 from July 25th 2024] points out that `armv7` is not a known, valid value for the `target_arch` cfg variable.  This is confirmed by the docs not listing it either: https://doc.rust-lang.org/reference/conditional-compilation.html#target_arch.
Hence drop this entirely, and rely purely on `target_arch = "arm"`.
Furthermore it also points out that we don't have a `test` and `api-level-30` feature: remove the unused `test` feature and reexpose `ConfigurationRef::screen_round()` which was behind a previously unsettable `feature = "api-level-30"`.
[Rust 1.80 from July 25th 2024]: https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html
---
EDIT: PR updated to fix **everything** that was holding back our CI.

Fix various codebase rots (stale CI, new Rust lints, broken MSRV checks by transitive dependency upgrades)

---

.github/workflows/ci.yml
android-activity/CHANGELOG.md
android-activity/Cargo.toml
android-activity/generate-bindings.sh

bindgen-cli 0.71 (which we want to use) requires rustc >= 1.70
If we're bumping the rust version anyway it looks like it makes sense to at least bump to 1.73 which happens to fix the `stat` struct definition for Android.
Technically since we run bindgen-cli offline, their minimum version doesn't _need_ to affect us but I'd rather just sync and not track multiple "minimum" versions for this crate.
Rust 1.73 was released October 2023, which is still well over a year old and very conservative.
This updates `generate-bindings.sh` to pass `--rust-target 1.73.0` so we avoid generating bindings that require a more recent compiler.

Bump rust-version to 1.73.0

---

android-activity/CHANGELOG.md
android-activity/src/lib.rs

Since we expose `ndk` types in the public API it makes sense to re-export these APIs so users of android-activity can defer to these without needing to manually sync the versions for explicit dependencies.

Re-export 'ndk' and 'ndk_sys' crates

---

.github/workflows/ci.yml
android-activity/Cargo.toml
android-activity/src/input/sdk.rs
android-activity/src/lib.rs

Build-test documentation and fix broken doc samples
